version: '3.8'

services:
    backend:
        build: .
        container_name: ken
        ports:
            - "5050:5000"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017/ken

    mongo:
        image: mongo:7
        container_name: ken-mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data: